repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: name-tests-test
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        exclude: ^(test_function.py|custom/mbingestion.py)$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        language: python
        types: [ python ]
        require_serial: true
        verbose: true
        entry: bash -c 'mypy "$@" || true' --
        exclude: custom/mbingestion.py
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - types-python-slugify

          # Security issues in Python code
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [ "-iii", "-ll" ]

  # Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3

  # Enforcing style consistency across Python projects
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=99
          - --ignore=D200,D202,PT009
          - --exclude=custom/mbingestion.py
        #          - --ignore=D100,D104,D107,D101,D106,D105,D102,D400,D103,S104,PT009,W503,S105,C416,N815,S311,A003,F401
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-mutable
          - flake8-print
          - flake8-simplify
          - flake8-bandit
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-mutable
          - flake8-pytest-style
          - mccabe
          - pep8-naming
          - pycodestyle
          - pyflakes
          - pylint

# Execução de testes
#  - repo: local
#    hooks:
#      - id: unittest
#        name: unittest
#        entry: venv/bin/python -m unittest discover -p "*test.py"
#        args:
#          - "--verbose"
#        language: python
#        types:
#          - python
#        pass_filenames: false
#        verbose: true
