x-deploy-limits: &deploy-limits
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: "1G"

services:
  app:
    build:
      context: .
    hostname: app
    container_name: app
    ports:
      - "8000:8000"
    restart: always
    <<: *deploy-limits
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:14.5
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_manager
    restart: always
    <<: *deploy-limits

volumes:
  pg_data: { }
