# Generated by Django 5.0.6 on 2024-05-26 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=60, verbose_name="key")),
                ("value", models.CharField(max_length=60, verbose_name="value")),
            ],
            options={
                "unique_together": {("key", "value")},
            },
        ),
    ]
