# Generated by Django 5.0.6 on 2024-05-26 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Nome"),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="Recurso",
                        max_length=50,
                        null=True,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("S", "Senior"), ("P", "Pleno"), ("J", "Junior")],
                        default="J",
                        max_length=1,
                        verbose_name="Nível",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-Mail"
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
            ],
            options={
                "ordering": ["id", "created_at", "updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Título do Projeto"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("N", "Não Iniciado"),
                            ("F", "Fazendo"),
                            ("V", "Em Validação"),
                            ("S", "Finalizado com Sucesso"),
                            ("C", "Cancelado"),
                            ("B", "Bloqueado (Aguardando)"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="Status do Projeto",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data Inicial")),
                ("dead_line", models.DateField(verbose_name="Dead Line")),
                ("overview", models.TextField(verbose_name="Visão Geral")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="project.client",
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "ordering": ["id", "created_at", "updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Título da Tarefa"
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("N", "Não Iniciado"),
                            ("F", "Fazendo"),
                            ("V", "Em Validação"),
                            ("S", "Finalizado com Sucesso"),
                            ("C", "Cancelado"),
                            ("B", "Bloqueado (Aguardando)"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data Estimada do Fim")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="project.project",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "ordering": ["id", "created_at", "updated_at"],
                "abstract": False,
            },
        ),
    ]
