"""# Generated by Django 5.0.6 on 2024-05-25 13:43"""

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Squad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Squad Name"
                    ),
                ),
            ],
            options={
                "ordering": ["id", "created_at", "updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Project Title"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("T", "Todo"),
                            ("D", "DOING"),
                            ("V", "Validation"),
                            ("S", "Success"),
                            ("C", "Cancelled"),
                            ("B", "Blocked"),
                        ],
                        default="T",
                        max_length=1,
                        verbose_name="Project Status",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("F", "Financial"),
                            ("T", "Eletrical"),
                            ("D", "Development"),
                            ("B", "Business"),
                            ("M", "Marketing"),
                        ],
                        max_length=1,
                        verbose_name="Project Type",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("dead_line", models.DateField(verbose_name="Deadline Date")),
                ("overview", models.TextField(verbose_name="Overview")),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="core.tag", verbose_name="Tags"
                    ),
                ),
            ],
            options={
                "ordering": ["id", "created_at", "updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-Mail"
                    ),
                ),
                (
                    "squad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project.squad",
                        verbose_name="Squad",
                    ),
                ),
            ],
            options={
                "ordering": ["id", "created_at", "updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Project Title"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("T", "Todo"),
                            ("D", "DOING"),
                            ("V", "Validation"),
                            ("S", "Success"),
                            ("C", "Cancelled"),
                            ("B", "Blocked"),
                        ],
                        default="T",
                        max_length=1,
                        verbose_name="Task Status",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Due Date")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project.client",
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="project.task",
                        verbose_name="Parent Task",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="core.tag", verbose_name="Tags"
                    ),
                ),
            ],
            options={
                "ordering": ["id", "created_at", "updated_at"],
                "abstract": False,
            },
        ),
    ]
