# Generated by Django 5.0.6 on 2024-05-26 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.AlterField(
            model_name="project",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="project.client",
                verbose_name="Responsável do Projeto",
            ),
        ),
    ]
