# Generated by Django 5.0.6 on 2024-05-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_remove_project_status_alter_project_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("N", "Não Iniciado"),
                    ("D", "Em Progresso"),
                    ("V", "Em Validação"),
                    ("S", "Finalizado com Sucesso"),
                    ("C", "Cancelado"),
                    ("B", "Bloqueado (Aguardando)"),
                ],
                default="N",
                max_length=1,
                verbose_name="Status",
            ),
        ),
    ]
